language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: KGULLnonIL9+b6UPnpwlkEYVAX5ErflPNhYpr4G3GFsp8M2BSDNd0AzhrgKAFRyKwY3TdSsYaBeDEQFvfaIF2MPzefqr4W6XdLiVh+E+1fxgN6kJIr0GTdRShoGrZGBtXkfrFjGwReQmF6EZq42HghSkdNY34/5UaI8SRbAPElXD60677OltI/ZY+NOpyuvzLsPMZZphHSOB+WGbZWqUFh2ZebrFvpB8ekcy43YHBT/goqImdaVbljxSbmwMoRtcdaSM2i4sfbtpCQggXIwll8yfFT2AppWEaFpzbBmTsKuX5rwux4H4kDpZS8K8434TdL7O5xt2vaW7GC8x5cjvdUbe4wfVVzbv4Mfc3dBo13VFXJQfxX2IGt9pn4FDsRL623SCSl4dbCqAkF/TMInOmzzWmKpfgvgM062m98wdHokRbLh5Aoc3KYjyZUOQzWZNg+mp29RDd4dnkxt3oW/A8nAG1HKfLdiA6H2xLTNPzjsDHU/l0ttwbCv9pwSLk5z7mbHrB8/UGH62d7tY21BJZ8yKYJQbeNjTIhDF01HtRhw6HqsRcXDBCXL2PzAXAzhL1mqHItXHqXNL29kuWYhobNjNlbXavET2jfXCBNQ6qecc2HjD+gv8LMaba9e3r6ft7/tZSv7ACiz0bx5sIltFnbtc3UaaJW3Fl4CdN+at7SY=
  app: album-discusser
  on:
    repo: krp312/backend-capstone-album-discusser